package hassdev

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Credentials persisted for integration scripts.
type Credentials struct {
	HAURL            string
	HAUser           string
	HAPass           string
	HAClientID       string
	HARefreshToken   string
	HAAccessToken    string
	HALongLivedToken string
	OTBRURL          string
}

func (c Credentials) Save(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), dirPerm); err != nil {
		return err
	}
	content := fmt.Sprintf(`# Generated by hassdev — do not commit.
HA_URL=%s
HA_USER=%s
HA_PASS=%s
HA_CLIENT_ID=%s
HA_REFRESH_TOKEN=%s
HA_ACCESS_TOKEN=%s
HA_LONG_LIVED_TOKEN=%s
OTBR_URL=%s
`, c.HAURL, c.HAUser, c.HAPass, c.HAClientID, c.HARefreshToken, c.HAAccessToken, c.HALongLivedToken, c.OTBRURL)
	return os.WriteFile(path, []byte(content), filePerm)
}

func LoadCredentials(path string) (Credentials, error) {
	data, err := os.ReadFile(path) //nolint:gosec // G304: path supplied by caller for local dev credentials file
	if err != nil {
		return Credentials{}, err
	}
	creds := parseCredentialsEnv(string(data))
	if creds.HALongLivedToken == "" {
		return creds, fmt.Errorf("HA_LONG_LIVED_TOKEN missing in %s", path)
	}
	return creds, nil
}

func parseCredentialsEnv(content string) Credentials {
	creds := Credentials{}
	for line := range strings.SplitSeq(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		applyCredentialKey(&creds, key, val)
	}
	return creds
}

func applyCredentialKey(creds *Credentials, key, val string) {
	switch key {
	case "HA_URL":
		creds.HAURL = val
	case "HA_USER":
		creds.HAUser = val
	case "HA_PASS":
		creds.HAPass = val
	case "HA_CLIENT_ID":
		creds.HAClientID = val
	case "HA_REFRESH_TOKEN":
		creds.HARefreshToken = val
	case "HA_ACCESS_TOKEN":
		creds.HAAccessToken = val
	case "HA_LONG_LIVED_TOKEN":
		creds.HALongLivedToken = val
	case "OTBR_URL":
		creds.OTBRURL = val
	}
}

func ReadRefreshTokenFromStorage(configDir, clientID string) (string, error) {
	path := filepath.Join(configDir, ".storage", "auth")
	data, err := os.ReadFile(path) //nolint:gosec // G304: path confined to HA config .storage/auth
	if err != nil {
		return "", err
	}
	var store struct {
		Data struct {
			RefreshTokens []struct {
				ClientID  *string `json:"client_id"`
				TokenType string  `json:"token_type"`
				Token     string  `json:"token"`
			} `json:"refresh_tokens"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &store); err != nil {
		return "", err
	}
	for i := len(store.Data.RefreshTokens) - 1; i >= 0; i-- {
		entry := store.Data.RefreshTokens[i]
		if entry.TokenType == "normal" && entry.ClientID != nil && *entry.ClientID == clientID {
			return entry.Token, nil
		}
	}
	return "", fmt.Errorf("refresh token not found for client %s", clientID)
}
